"""Initial migration.

Revision ID: 49cd593f2c34
Revises: 76efdc3b06f6
Create Date: 2022-02-07 12:24:06.820996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cd593f2c34'
down_revision = '76efdc3b06f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'товары', ['code_of_item'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'товары', type_='unique')
    # ### end Alembic commands ###
