"""Initial migration.

Revision ID: 76efdc3b06f6
Revises: 99c074749bf8
Create Date: 2022-02-07 12:17:09.639433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76efdc3b06f6'
down_revision = '99c074749bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('товары',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_of_item', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_fondy', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('товары')
    # ### end Alembic commands ###
